In [1]:
import requests
from bs4 import BeautifulSoup
import csv
import time
import pandas as pd
import lxml
import re
import numpy as np

In [2]:
a=pd.read_csv('groupstandings.csv')
a.set_index('Group')

                  Team  W  L    RF/RA  RD
Group
Group A         Cloud9  5  0  154/101  53
Group A      The Guard  4  1  143/115  28
Group A           XSET  3  2  140/127  13
Group A     Luminosity  2  3  120/143 -23
Group A    100 Thieves  1  4  127/153 -26
Group A  Evil Geniuses  0  5  106/151 -45
Group B       Version1  5  0   144/92  52
Group B   OpTic Gaming  3  2  143/114  29
Group B      Sentinels  3  2  149/155  -6
Group B        Knights  2  3  107/132 -25
Group B    NRG Esports  1  4  131/145 -14
Group B           Rise  1  4  109/145 -36

In [3]:
matchresults = pd.read_csv('groupmatchresults.csv')
matchresults.iloc[16]

URL       /69879/sentinels-vs-nrg-esports-champions-tour...
Winner                                                  SEN
Loser                                                   NRG
Score                                             ['2' '1']
Name: 16, dtype: object

In [4]:
test = matchresults.iloc[16]
url = "https://www.vlr.gg"+test.URL
result = requests.get(url)
soupparser = BeautifulSoup(result.text,'lxml')
url

'https://www.vlr.gg/69879/sentinels-vs-nrg-esports-champions-tour-north-america-stage-1-challengers-w1'

In [13]:
def get_series_info(mapsstats_soup):
    maps_header =mapsstats_soup.find("div",class_="vm-stats-gamesnav noselect")
    series_list = []
    for map_name in maps_header.contents[3:9:2]:
        eachmap_dict = {"Map No.":map_name.text.strip().split()[0],"Map Name":map_name.text.strip().split()[1],
                   "Map ID":map_name["data-game-id"]}
        series_list.append(eachmap_dict)
    return series_list

# Portion of website with only map/stats
maps_stats_soup = soupparser.find("div",class_="vm-stats")
seriesinfo = get_series_info(maps_stats_soup)

In [14]:
seriesinfo

[{'Map No.': '1', 'Map Name': 'Fracture', 'Map ID': '70814'},
 {'Map No.': '2', 'Map Name': 'Haven', 'Map ID': '70815'},
 {'Map No.': '3', 'Map Name': 'Bind', 'Map ID': '70816'}]

In [79]:
def extract_team_overview(overview_oneteam_soup):
    # Extract header and stats table body
    oneteam_header = overview_oneteam_soup.find("thead")
    oneteam_body = overview_oneteam_soup.find("tbody").find_all("tr")
    
    oneteam_list= []
    for player in oneteam_body:
        player_stat_list = []
        # Get all the stats in a player row
        for stat in player.find_all("td"):
            stattext = stat.text.strip()
            if stattext != "":
                player_stat_list.append((stattext))
                
        # Regex to nicely format team name and player name
        findteamname = re.compile("[A-Za-z0-9 ]+")
        playerandteam =  re.findall(findteamname, player_stat_list[0]) 
        playerandteam.append(player.find("img")['title'])
        player_stat_list = playerandteam + player_stat_list[1:]
        oneteam_list.append(player_stat_list)

    colnames = ["Player","Team","Agent"]+[colname.text.strip() for colname in oneteam_header.find_all("th") if colname.text.strip()!=""]
    colnames[-1] = "FK +/-"
    
    df = pd.DataFrame(oneteam_list)
    df.columns =  colnames

    statsonly_df = df.iloc[:,3:]
    statsonly_df = statsonly_df.applymap(lambda row:row.strip().split('\n'))
    statsonly_df.loc[:,"D"] = statsonly_df.apply(lambda row:row["D"][2:5],axis=1)
    
    all3 = []
    sides_list = ["All","Atk","Def"]
    for side_ind in np.arange(len(sides_list)):
        side_statsonly_df = statsonly_df.applymap(lambda cell: cell[side_ind])
        side_statsonly_df["Side"] = sides_list[side_ind]
        side_statsonly_df = pd.concat([df.iloc[:,:3],side_statsonly_df],axis=1)
        all3.append(side_statsonly_df)
    
    return pd.concat(all3,ignore_index=True) 


def combine_teams_overview(mapsstats_soup,seriesinfo):
    
    statscontainer = mapsstats_soup.find("div",class_="vm-stats-container")
    bo3 = []
    for game in seriesinfo:
        gamesoup = statscontainer.find("div",attrs={"class":"vm-stats-game","data-game-id":game["Map ID"]})
        bothteams_soup  = gamesoup.find_all("table",class_="wf-table-inset mod-overview")
        team1 = extract_team_overview(bothteams_soup[0])
        team2 = extract_team_overview(bothteams_soup[1])
        bothteams_df = pd.concat([team1,team2],ignore_index=True)
        bothteams_df["Map"] = "-".join(game.values())
        bo3.append(bothteams_df)
        
    final_df = pd.concat(bo3,ignore_index=True)
    final_df = final_df.set_index(["Side","Map","Team"])
    return final_df




a=combine_teams_overview(maps_stats_soup,seriesinfo)

In [80]:
a.loc['All']

                         Player    Agent  ACS   K   D   A  +/– KAST  ADR  HS%  \
Map              Team
1-Fracture-70814 SEN      dapr   chamber  226  20  18   1   +2  74%  127  18%
                 SEN      TenZ      jett  205  18  14   5   +4  78%  128  20%
                 SEN     zombs     viper  205  15  16  10   -1  65%  133  29%
                 SEN   ShahZaM    breach  203  16  15   5   +1  78%  137  30%
                 SEN      SicK     astra  171  12  21   7   -9  61%  121  36%
                 NRG       tex   chamber  237  18  20   5   -2  78%  152  32%
                 NRG   ANDROID     viper  236  19  14   7   +5  74%  152  20%
                 NRG       s0m      jett  212  18  18   3    0  57%  139  32%
                 NRG      eeiu    breach  180  14  14   8    0  70%  129  30%
                 NRG     hazed     astra  169  15  15   7    0  74%  100  32%
2-Haven-70815    SEN      TenZ      jett  283  25  18   2   +7  71%  175  28%
                 SEN   ShahZaM      sova  266  21  16   7   +5  83%  190  32%
                 SEN      SicK      skye  239  20  18   5   +2  67%  168  32%
                 SEN     zombs     astra  166  15  17   8   -2  75%  115  21%
                 SEN      dapr    cypher  105   6  17   8  -11  67%   76  16%
                 NRG       s0m      jett  285  24  17   6   +7  79%  169  25%
                 NRG      eeiu      sova  211  17  20  10   -3  79%  143  14%
                 NRG   ANDROID   chamber  200  20  16   2   +4  71%  141  38%
                 NRG       tex      kayo  192  16  18  11   -2  63%  121  33%
                 NRG     hazed     astra  120   9  16   8   -7  63%   90  14%
3-Bind-70816     SEN      TenZ      jett  306  23  15   3   +8  68%  185  21%
                 SEN      SicK      raze  226  18  14   4   +4  68%  156  20%
                 SEN      dapr     viper  182  13  16   8   -3  68%  141  17%
                 SEN   ShahZaM      sova  182  14  11   8   +3  82%  130  39%
                 SEN     zombs     astra  151  14  13   3   +1  73%   97  23%
                 NRG      eeiu      sova  237  15  16  16   -1  77%  169  22%
                 NRG   ANDROID     viper  184  15  15   4    0  68%  124  27%
                 NRG       s0m      jett  172  15  16   0   -1  55%   97  18%
                 NRG     hazed     astra  152  13  17   4   -4  55%   92  33%
                 NRG       tex      skye  136  11  18   5   -7  64%  103  35%

                      FK FD FK +/-
Map              Team
1-Fracture-70814 SEN   3  2     +1
                 SEN   2  7     -5
                 SEN   1  2     -1
                 SEN   3  1     +2
                 SEN   0  2     -2
                 NRG   5  0     +5
                 NRG   1  0     +1
                 NRG   4  5     -1
                 NRG   1  1      0
                 NRG   3  3      0
2-Haven-70815    SEN   5  2     +3
                 SEN   1  2     -1
                 SEN   4  5     -1
                 SEN   0  1     -1
                 SEN   0  4     -4
                 NRG   7  4     +3
                 NRG   1  1      0
                 NRG   1  1      0
                 NRG   4  2     +2
                 NRG   1  2     -1
3-Bind-70816     SEN   7  2     +5
                 SEN   3  1     +2
                 SEN   1  4     -3
                 SEN   1  1      0
                 SEN   0  2     -2
                 NRG   0  0      0
                 NRG   2  2      0
                 NRG   6  5     +1
                 NRG   1  2     -1
                 NRG   1  3     -2

In [7]:
# def torctorboth(row):
#     return row
    

# def extract_team_overview(overview_oneteam_soup):
#     oneteam_header = overview_oneteam_soup.find("thead")
#     oneteam_body = overview_oneteam_soup.find("tbody").find_all("tr")
#     oneteam_list= []
#     for i in oneteam_body:
#         player_stat = []
#         for stat in i.find_all("td"):
#             stattext = stat.text.strip()
#             if stattext != "":
#                 player_stat.append((stattext))

#         findteamname = re.compile("[A-Za-z0-9 ]+")
#         playerandteam =  re.findall(findteamname, player_stat[0])   
#         player_stat[0] = playerandteam[0].strip()
#         player_stat.insert(1,playerandteam[1])
#         player_stat.insert(2,i.find("img")['title'])
#         oneteam_list.append(player_stat)

#     colnames = [colname.text.strip() for colname in oneteam_header.find_all("th") if colname.text.strip()!=""]
#     colnames_a= ["Player","Team","Agent"]
#     colnames_a.extend(colnames)
#     colnames_a[-1] = "FK +/-"
    
#     df = pd.DataFrame(oneteam_list)
#     df.columns =  colnames_a
    
#     temp_df = df.iloc[:,3:]
#     temp_df = temp_df.applymap(lambda row:row.strip().split('\n'))
#     temp_df.loc[:,"D"] = temp_df.apply(lambda row:row["D"][2:5],axis=1)

#     return temp_df.apply(torctorboth,axis= 0)


# def combine_teams_overview(mapsstats_soup,seriesinfo):
    
#     statscontainer = mapsstats_soup.find("div",class_="vm-stats-container")
#     for game in seriesinfo:
#         #print(game)
#         gamesoup = statscontainer.find("div",attrs={"class":"vm-stats-game","data-game-id":game["Map ID"]})
#         bothteams  = gamesoup.find_all("table",class_="wf-table-inset mod-overview")
#         c=pd.concat([extract_team_overview(bothteams[0])])#,(extract_team_overview(bothteams[1]))])
#         break
#     return c




# combine_teams_overview(maps_stats_soup,seriesinfo)#['ACS'][0].split('\n')
# #sen=extract_team_overview(oneteam[0])

,ACS,K,D,A,+/–,KAST,ADR,HS%,FK,FD,FK +/-
0,"[226, 240, 212]","[20, 10, 10]","[18, 11, 7]","[1, 1, 0]","[+2, -1, +3]","[74%, 67%, 82%]","[127, 130, 122]","[18%, 18%, 18%]","[3, 1, 2]","[2, 1, 1]","[+1, 0, +1]"
1,"[205, 135, 282]","[18, 5, 13]","[14, 8, 6]","[5, 2, 3]","[+4, -3, +7]","[78%, 67%, 91%]","[128, 97, 161]","[20%, 21%, 20%]","[2, 0, 2]","[7, 1, 6]","[-5, -1, -4]"
2,"[205, 189, 223]","[15, 7, 8]","[16, 9, 7]","[10, 7, 3]","[-1, -2, +1]","[65%, 67%, 64%]","[133, 108, 161]","[29%, 17%, 41%]","[1, 1, 0]","[2, 1, 1]","[-1, 0, -1]"
3,"[203, 122, 293]","[16, 5, 11]","[15, 9, 6]","[5, 2, 3]","[+1, -4, +5]","[78%, 67%, 91%]","[137, 69, 212]","[30%, 36%, 28%]","[3, 1, 2]","[1, 1, 0]","[+2, 0, +2]"
4,"[171, 212, 127]","[12, 8, 4]","[21, 12, 9]","[7, 2, 5]","[-9, -4, -5]","[61%, 58%, 64%]","[121, 142, 98]","[36%, 45%, 27%]","[0, 0, 0]","[2, 1, 1]","[-2, -1, -1]"